# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e3a82eabea6aaa0d4c43a8ceea4cebddaf5ce2c715f0b55fe8e7992593cab4d108f49c3d20b19e559dc729bce771e7f6f625a5f9f3c7f615cab0c84fac4207

test:
  secret_key_base: d20e899d83376425dc1aacf5616e022796158add855cacd79e6ab2087f8695ba3c780a9c178dc1bcb84d80147275aaa95c53635d4c6e9645d3910ae06ae98471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
